version: '3.8'

services:
  postgres: 
    image: postgres:14
    container_name: retail_postgres
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_pass
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data      #mount CSV data folder
      - ./sql:/sql        #mount SQL scripts folder 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: